name: Build and Test

on:
  workflow_call:
    inputs:
      CONFIG:
        required: false
        type: string
        default: Debug
      VERSION:
        required: false
        type: string
        default: 0.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ inputs.CONFIG }} /p:Version=${{ inputs.VERSION }}
    - name: Test
      run: dotnet test --no-restore --configuration ${{ inputs.CONFIG }} /p:Version=${{ inputs.VERSION }} --no-build
      
